const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=(n,d=0)=>Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:d});
const state={scale:'commune',metric:'vegetation_pct',selected:null,data:{},layer:null,tooltip:null};
const metrics={
 vegetation_pct:{title:'Part du territoire végétalisée',unit:' %',colors:['#f2f6ed','#c9dfb8','#86b36f','#39784d'],note:'Bois, forêts, landes, peupleraies et vergers décrits par la BD TOPO.',value:p=>p.vegetation_pct},
 reservoir_pct:{title:'Part en réservoirs de nature',unit:' %',colors:['#f1f5ef','#b7d1b9','#699b73','#205c3a'],note:'Emprise cumulée sans double compte des ZNIEFF et espaces protégés.',value:p=>p.reservoir_pct},
 connections:{title:'Connexions écologiques repérées',unit:'',colors:['#fbf4e7','#e8c98e','#ce9443','#955d18'],note:'Nombre de connexions écologiques régionales localisées dans le territoire.',value:p=>p.connections},
 water_density:{title:'Densité du réseau hydrographique',unit:' km/km²',colors:['#eef7f9','#b9dbe5','#6eafc7','#24779e'],note:'Longueur de cours d’eau rapportée à la surface du territoire.',value:p=>p.water_density},
 freshness:{title:'Appuis potentiels de fraîcheur',unit:'',colors:['#f4f5e9','#c6d9a7','#78ad7a','#26706b'],note:'Lecture relative croisant végétation et eau ; ce n’est pas une température mesurée.',value:p=>p.freshness_score}
};
const map=L.map('map',{zoomControl:false,preferCanvas:true}).setView([49.08,2.15],10);L.control.zoom({position:'topright'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);

function withScores(profiles){const vals=Object.values(profiles),maxWater=Math.max(...vals.map(p=>p.water_density),1);vals.forEach(p=>{p.freshness_score=.7*(p.vegetation_pct/100)+.3*Math.min(1,p.water_density/maxWater)});return profiles}
async function load(){try{const [communes,epcis,cp,ep]=await Promise.all(['communes_95.geojson','epcis_95.geojson','commune_profiles.json','epci_profiles.json'].map(n=>fetch(`data/${n}`).then(r=>{if(!r.ok)throw Error(n);return r.json()})));state.data={communes,epcis,communeProfiles:withScores(cp),epciProfiles:withScores(ep)};renderLayer();fitAll();$('mapStatus').textContent='Carte prête · survolez puis cliquez sur un territoire';bind();}catch(e){console.error(e);$('mapStatus').textContent='Certaines données ne sont pas disponibles';}}
function profiles(){return state.scale==='commune'?state.data.communeProfiles:state.data.epciProfiles}function geo(){return state.scale==='commune'?state.data.communes:state.data.epcis}
function values(){return Object.values(profiles()).map(p=>metrics[state.metric].value(p)).filter(Number.isFinite).sort((a,b)=>a-b)}
function breaks(){const v=values();return [v[Math.floor(v.length*.25)]||0,v[Math.floor(v.length*.5)]||0,v[Math.floor(v.length*.75)]||0]}
function color(value){const b=breaks(),c=metrics[state.metric].colors;return value<=b[0]?c[0]:value<=b[1]?c[1]:value<=b[2]?c[2]:c[3]}
function style(feature){const p=profiles()[feature.properties.code],selected=state.selected===feature.properties.code;return{color:selected?'#122d1c':'#fff',weight:selected?3:state.scale==='epci'?1.6:1,fillColor:color(metrics[state.metric].value(p||{})),fillOpacity:.78}}
function displayValue(p){const m=metrics[state.metric],v=m.value(p);if(state.metric==='freshness'){const all=values(),rank=all.filter(x=>x<=v).length/all.length;return rank>.66?'Appuis forts':rank>.33?'Appuis intermédiaires':'Appuis plus limités'}return `${fmt(v,state.metric==='water_density'?2:1)}${m.unit}`}
function renderLayer(){if(state.layer)map.removeLayer(state.layer);state.tooltip=L.tooltip({sticky:true,direction:'top',className:'nature-tooltip'});state.layer=L.geoJSON(geo(),{style,onEachFeature:(f,l)=>{const p=profiles()[f.properties.code];l.on({mouseover:e=>{e.target.setStyle({weight:3,color:'#183820',fillOpacity:.95});e.target.bringToFront();state.tooltip.setLatLng(e.latlng).setContent(`<strong>${esc(p?.name||f.properties.nom)}</strong><br>${esc(displayValue(p))}`).addTo(map)},mousemove:e=>state.tooltip.setLatLng(e.latlng),mouseout:e=>{map.removeLayer(state.tooltip);state.layer.resetStyle(e.target)},click:()=>select(f.properties.code,true)})}}).addTo(map);updateLegend();}
function updateLegend(){const m=metrics[state.metric],v=values();$('mapLegend').querySelector('strong').textContent=m.title;$('mapLegend').querySelector('.ramp').style.background=`linear-gradient(90deg,${m.colors.join(',')})`;const labs=$('mapLegend').querySelectorAll('.ramp-labels span');labs[0].textContent=state.metric==='freshness'?'Plus limité':`${fmt(v[0],1)}${m.unit}`;labs[1].textContent=state.metric==='freshness'?'Plus favorable':`${fmt(v.at(-1),1)}${m.unit}`;$('mapLegend').querySelector('p').textContent=m.note}
function fitAll(){if(state.layer)map.fitBounds(state.layer.getBounds(),{padding:[20,20],animate:false})}
function profileText(p){if(p.vegetation_pct>=45)return'Un socle végétal important structure ce territoire et peut soutenir plusieurs continuités écologiques.';if(p.vegetation_pct>=25)return'Le territoire dispose d’appuis naturels réels, mais leur connexion et leur proximité avec les espaces habités restent déterminantes.';return'Le couvert végétalisé est plus contraint : les vallées, parcs et liaisons résiduelles jouent ici un rôle particulièrement précieux.'}
function select(code,zoom=false){const p=profiles()[code];if(!p)return;state.selected=code;state.layer.setStyle(style);if(zoom){state.layer.eachLayer(l=>{if(l.feature.properties.code===code)map.fitBounds(l.getBounds(),{padding:[50,50],maxZoom:12})})}renderDetail(p);}
function renderDetail(p){
 const water=p.water_density>=1?'Un réseau hydrographique dense renforce les appuis bleus du territoire.':'Chaque vallée et cours d’eau joue ici un rôle important dans la continuité locale.';
 const link=p.connections?`${p.connections} connexion${p.connections>1?'s':''} d’intérêt régional y ${p.connections>1?'sont repérées':'est repérée'}.`:'Aucune connexion régionale ponctuelle n’est repérée à cette échelle.';
 $('detailContent').innerHTML=`<span class="detail-tag">PORTRAIT ${state.scale==='commune'?'COMMUNAL':'INTERCOMMUNAL'}</span><h2>${esc(p.name)}</h2><p class="subtitle">${profileText(p)}</p><div class="kpi-grid"><div class="kpi-tile"><small>Couvert végétalisé</small><strong>${fmt(p.vegetation_pct,1)} %</strong><em>${fmt(p.vegetation_ha)} ha</em></div><div class="kpi-tile"><small>Réservoirs de nature</small><strong>${fmt(p.reservoir_pct,1)} %</strong><em>${fmt(p.reservoir_ha)} ha</em></div><div class="kpi-tile"><small>Cours d’eau</small><strong>${fmt(p.water_km,1)} km</strong><em>${fmt(p.water_density,2)} km/km²</em></div><div class="kpi-tile ${p.connections?'':'warn'}"><small>Connexions régionales</small><strong>${fmt(p.connections)}</strong><em>SDRIF-E</em></div></div><div class="section-block"><strong>Clés de lecture</strong><div class="flag-note">${water}</div><div class="flag-note">${link}</div></div><div class="section-block"><strong>Connaissance naturaliste</strong><p class="subtitle">${fmt(p.observations)} observations agrégées dans les mailles intersectées${p.last_observation?`, dernière observation ${p.last_observation}`:''}. L’effort de prospection varie selon les secteurs.</p></div><a class="profile-link" href="fiche.html?type=${state.scale}&id=${encodeURIComponent(p.code)}">Ouvrir la fiche territoriale <span>→</span></a><button id="centerSelected" class="sources-inline" style="width:100%;margin-top:8px">Recentrer sur le territoire</button>`;
 $('detailPanel').classList.add('open');$('centerSelected').onclick=()=>select(p.code,true)
}
function setScale(scale){state.scale=scale;state.selected=null;document.querySelectorAll('[data-scale]').forEach(b=>{const active=b.dataset.scale===scale;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});$('territorySearchLabel').textContent=scale==='commune'?'Rechercher une commune':'Rechercher un EPCI';$('searchInput').placeholder=scale==='commune'?'Ex. Pontoise':'Ex. Vexin centre';$('detailPanel').classList.remove('open');renderLayer();fitAll()}
function setMetric(metric){state.metric=metric;document.querySelectorAll('[data-layer]').forEach(b=>b.classList.toggle('active',b.dataset.layer===metric));state.layer.setStyle(style);updateLegend();if(state.selected)renderDetail(profiles()[state.selected])}
function search(q){const clean=s=>s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase(),items=Object.values(profiles()).filter(p=>clean(p.name).includes(clean(q))).slice(0,8);const box=$('searchResults');box.innerHTML=items.map(p=>`<button data-result="${p.code}">${esc(p.name)}</button>`).join('');box.hidden=!q||!items.length;box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.hidden=true;$('searchInput').value=profiles()[b.dataset.result].name;select(b.dataset.result,true)})}
function bind(){document.querySelectorAll('[data-scale]').forEach(b=>b.onclick=()=>setScale(b.dataset.scale));document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>setMetric(b.dataset.layer));$('searchInput').oninput=e=>search(e.target.value);$('searchButton').onclick=e=>{e.preventDefault();const p=Object.values(profiles()).find(p=>p.name.toLowerCase()===$('searchInput').value.toLowerCase())||Object.values(profiles()).find(p=>p.name.toLowerCase().includes($('searchInput').value.toLowerCase()));if(p)select(p.code,true)};$('resetView').onclick=fitAll;$('closeDetail').onclick=()=>$('detailPanel').classList.remove('open');$('openData').onclick=$('openDataTop').onclick=()=>state.selected?renderDetail(profiles()[state.selected]):$('methodDialog').showModal();$('openMethod').onclick=()=>$('methodDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('mobileLayers').onclick=()=>{const open=$('layerSidebar').classList.toggle('open');$('mobileLayers').setAttribute('aria-expanded',open)}}
load();
