const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=(n,d=0)=>Number(n||0).toLocaleString('fr-FR',{maximumFractionDigits:d});
const state={scale:'commune',metric:'vegetation_pct',selected:null,data:{},layer:null,tooltip:null};
const metrics={
 vegetation_pct:{title:'Part du territoire végétalisée',unit:' %',colors:['#f2f6ed','#c9dfb8','#86b36f','#39784d'],note:'Bois, forêts, landes, peupleraies et vergers décrits par la BD TOPO.',value:p=>p.vegetation_pct},
 reservoir_pct:{title:'Part en réservoirs de nature',unit:' %',colors:['#f1f5ef','#b7d1b9','#699b73','#205c3a'],note:'Emprise cumulée sans double compte des ZNIEFF et espaces protégés.',value:p=>p.reservoir_pct},
 connections:{title:'Connexions écologiques repérées',unit:'',colors:['#fbf4e7','#e8c98e','#ce9443','#955d18'],note:'Nombre de connexions écologiques régionales localisées dans le territoire.',value:p=>p.connections},
 water_density:{title:'Densité du réseau hydrographique',unit:' km/km²',colors:['#eef7f9','#b9dbe5','#6eafc7','#24779e'],note:'Longueur de cours d’eau rapportée à la surface du territoire.',value:p=>p.water_density},
 freshness:{title:'Appuis potentiels de fraîcheur',unit:'',colors:['#f4f5e9','#c6d9a7','#78ad7a','#26706b'],note:'Lecture relative croisant végétation et eau ; ce n’est pas une température mesurée.',value:p=>p.freshness_score}
};
const map=L.map('map',{zoomControl:false,preferCanvas:true}).setView([49.08,2.15],10);L.control.zoom({position:'topright'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);

function withScores(profiles){const vals=Object.values(profiles),maxWater=Math.max(...vals.map(p=>p.water_density),1);vals.forEach(p=>{p.freshness_score=.7*(p.vegetation_pct/100)+.3*Math.min(1,p.water_density/maxWater)});return profiles}
async function load(){try{const [communes,epcis,cp,ep]=await Promise.all(['communes_95.geojson','epcis_95.geojson','commune_profiles.json','epci_profiles.json'].map(n=>fetch(`data/${n}`).then(r=>{if(!r.ok)throw Error(n);return r.json()})));state.data={communes,epcis,communeProfiles:withScores(cp),epciProfiles:withScores(ep)};renderLayer();fitAll();$('mapStatus').textContent='Carte prête · survolez puis cliquez sur un territoire';bind();}catch(e){console.error(e);$('mapStatus').textContent='Certaines données ne sont pas disponibles';}}
function profiles(){return state.scale==='commune'?state.data.communeProfiles:state.data.epciProfiles}function geo(){return state.scale==='commune'?state.data.communes:state.data.epcis}
function values(){return Object.values(profiles()).map(p=>metrics[state.metric].value(p)).filter(Number.isFinite).sort((a,b)=>a-b)}
function breaks(){const v=values();return [v[Math.floor(v.length*.25)]||0,v[Math.floor(v.length*.5)]||0,v[Math.floor(v.length*.75)]||0]}
function color(value){const b=breaks(),c=metrics[state.metric].colors;return value<=b[0]?c[0]:value<=b[1]?c[1]:value<=b[2]?c[2]:c[3]}
function style(feature){const p=profiles()[feature.properties.code],selected=state.selected===feature.properties.code;return{color:selected?'#122d1c':'#fff',weight:selected?3:state.scale==='epci'?1.6:1,fillColor:color(metrics[state.metric].value(p||{})),fillOpacity:.78}}
function displayValue(p){const m=metrics[state.metric],v=m.value(p);if(state.metric==='freshness'){const all=values(),rank=all.filter(x=>x<=v).length/all.length;return rank>.66?'Appuis forts':rank>.33?'Appuis intermédiaires':'Appuis plus limités'}return `${fmt(v,state.metric==='water_density'?2:1)}${m.unit}`}
function renderLayer(){if(state.layer)map.removeLayer(state.layer);state.tooltip=L.tooltip({sticky:true,direction:'top',className:'nature-tooltip'});state.layer=L.geoJSON(geo(),{style,onEachFeature:(f,l)=>{const p=profiles()[f.properties.code];l.on({mouseover:e=>{e.target.setStyle({weight:3,color:'#183820',fillOpacity:.95});e.target.bringToFront();state.tooltip.setLatLng(e.latlng).setContent(`<strong>${esc(p?.name||f.properties.nom)}</strong><br>${esc(displayValue(p))}`).addTo(map)},mousemove:e=>state.tooltip.setLatLng(e.latlng),mouseout:e=>{map.removeLayer(state.tooltip);state.layer.resetStyle(e.target)},click:()=>select(f.properties.code,true)})}}).addTo(map);updateLegend();}
function updateLegend(){const m=metrics[state.metric],v=values();$('mapLegend').querySelector('strong').textContent=m.title;$('mapLegend').querySelector('.ramp').style.background=`linear-gradient(90deg,${m.colors.join(',')})`;const labs=$('mapLegend').querySelectorAll('.ramp-labels span');labs[0].textContent=state.metric==='freshness'?'Plus limité':`${fmt(v[0],1)}${m.unit}`;labs[1].textContent=state.metric==='freshness'?'Plus favorable':`${fmt(v.at(-1),1)}${m.unit}`;$('mapLegend').querySelector('p').textContent=m.note}
function fitAll(){if(state.layer)map.fitBounds(state.layer.getBounds(),{padding:[20,20],animate:false})}
function profileText(p){if(p.vegetation_pct>=45)return'Un socle végétal important structure ce territoire et peut soutenir plusieurs continuités écologiques.';if(p.vegetation_pct>=25)return'Le territoire dispose d’appuis naturels réels, mais leur connexion et leur proximité avec les espaces habités restent déterminantes.';return'Le couvert végétalisé est plus contraint : les vallées, parcs et liaisons résiduelles jouent ici un rôle particulièrement précieux.'}
function select(code,zoom=false){const p=profiles()[code];if(!p)return;state.selected=code;state.layer.setStyle(style);if(zoom){state.layer.eachLayer(l=>{if(l.feature.properties.code===code)map.fitBounds(l.getBounds(),{padding:[50,50],maxZoom:12})})}renderDetail(p);}
function renderDetail(p){
 const share=Math.max(0,Math.min(100,p.vegetation_pct)),profile=share>=45?'Territoire à dominante naturelle':share>=25?'Territoire aux appuis naturels contrastés':'Territoire où les continuités sont précieuses';
 const balance=p.vegetation_pct-p.reservoir_pct,balanceText=balance>20?'Le couvert végétalisé dépasse largement les espaces inventoriés.':'Les réservoirs reconnus occupent une place importante dans le couvert naturel.';
 const waterWidth=Math.min(100,p.water_km/Math.max(1,p.water_km)*100),connectionWidth=Math.min(100,Math.max(8,p.connections*12));
 $('detailContent').innerHTML=`<span class="detail-tag">${state.scale==='commune'?'COMMUNE':'EPCI'} · NATURE · VAL-D’OISE</span><h2>${esc(p.name)}</h2><p class="subtitle">Continuités écologiques · eau · végétation · référentiels 2026</p><div class="property-grid"><div class="property out"><small>COUVERT VÉGÉTALISÉ</small><strong>${fmt(p.vegetation_pct,1)} %</strong><span>${fmt(p.vegetation_ha)} hectares</span></div><div class="property"><small>RÉSERVOIRS DE NATURE</small><strong>${fmt(p.reservoir_pct,1)} %</strong><span>${fmt(p.reservoir_ha)} hectares</span></div></div><section class="flow-profile" style="--out-share:${share*3.6}deg"><div class="flow-donut"><div><strong>${fmt(share)}%</strong><small>végétalisé</small></div></div><div class="profile-copy"><span>PROFIL NATUREL</span><strong>${profile}</strong><p>${fmt(p.water_km,1)} km de cours d’eau · ${fmt(p.connections)} connexion${p.connections>1?'s':''} régionale${p.connections>1?'s':''}</p></div></section><section class="balance-card ${balance>=0?'positive':'negative'}"><div><span>ÉQUILIBRE DES APPUIS</span><strong>${balance>=0?'+':''}${fmt(balance,1)} pts</strong></div><p>${balanceText}</p><div class="balance-track"><i style="width:${share}%"></i><b style="width:${Math.max(0,100-share)}%"></b></div></section><div class="trajectory-card"><strong>EAU ET CONTINUITÉS</strong><div class="trajectory-row"><span class="rank-index">01</span><div class="rank-copy"><b>Réseau hydrographique</b><i style="--bar:${waterWidth}%"></i></div><span>${fmt(p.water_km,1)} km</span></div><div class="trajectory-row"><span class="rank-index">02</span><div class="rank-copy"><b>Connexions SDRIF-E</b><i style="--bar:${connectionWidth}%"></i></div><span>${fmt(p.connections)}</span></div></div><div class="trajectory-card"><strong>CONNAISSANCE NATURALISTE</strong><div class="trajectory-row"><span class="rank-index">01</span><div class="rank-copy"><b>Observations agrégées</b><i style="--bar:100%"></i></div><span>${fmt(p.observations)}</span></div><div class="trajectory-row"><span class="rank-index">02</span><div class="rank-copy"><b>Dernière observation</b><i style="--bar:78%"></i></div><span>${p.last_observation||'—'}</span></div></div><a class="profile-link" href="fiche.html?type=${state.scale}&id=${encodeURIComponent(p.code)}">Voir la fiche ${state.scale==='commune'?'communale':'intercommunale'} complète et le PDF <span>↗</span></a><p class="detail-method">Valeurs calculées par intersection géographique des référentiels publics. Les observations reflètent aussi l’effort de prospection.</p>`;
 $('detailPanel').classList.add('open')
}
function setScale(scale){state.scale=scale;state.selected=null;document.querySelectorAll('[data-scale]').forEach(b=>{const active=b.dataset.scale===scale;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});$('territorySearchLabel').textContent=scale==='commune'?'Rechercher une commune':'Rechercher un EPCI';$('searchInput').placeholder=scale==='commune'?'Ex. Pontoise':'Ex. Vexin centre';$('detailPanel').classList.remove('open');renderLayer();fitAll()}
function setMetric(metric){state.metric=metric;document.querySelectorAll('[data-layer]').forEach(b=>b.classList.toggle('active',b.dataset.layer===metric));state.layer.setStyle(style);updateLegend();if(state.selected)renderDetail(profiles()[state.selected])}
function search(q){const clean=s=>s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase(),items=Object.values(profiles()).filter(p=>clean(p.name).includes(clean(q))).slice(0,8);const box=$('searchResults');box.innerHTML=items.map(p=>`<button data-result="${p.code}">${esc(p.name)}</button>`).join('');box.hidden=!q||!items.length;box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.hidden=true;$('searchInput').value=profiles()[b.dataset.result].name;select(b.dataset.result,true)})}
function bind(){document.querySelectorAll('[data-scale]').forEach(b=>b.onclick=()=>setScale(b.dataset.scale));document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>setMetric(b.dataset.layer));$('searchInput').oninput=e=>search(e.target.value);$('searchButton').onclick=e=>{e.preventDefault();const p=Object.values(profiles()).find(p=>p.name.toLowerCase()===$('searchInput').value.toLowerCase())||Object.values(profiles()).find(p=>p.name.toLowerCase().includes($('searchInput').value.toLowerCase()));if(p)select(p.code,true)};$('resetView').onclick=fitAll;$('closeDetail').onclick=()=>$('detailPanel').classList.remove('open');$('openData').onclick=$('openDataTop').onclick=()=>state.selected?renderDetail(profiles()[state.selected]):$('methodDialog').showModal();$('openMethod').onclick=()=>$('methodDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('mobileLayers').onclick=()=>{const open=$('layerSidebar').classList.toggle('open');$('mobileLayers').setAttribute('aria-expanded',open)}}
load();
