(function(){
 "use strict";
 const root=document.getElementById("profileRoot"),dialog=document.getElementById("exportDialog"),headerTitle=document.getElementById("headerTitle");
 const params=new URLSearchParams(location.search),type=params.get("type")==="epci"?"epci":"commune",id=params.get("id")||params.get("code");let currentProfile;
 const fmt=(n,d=0)=>Number(n||0).toLocaleString("fr-FR",{maximumFractionDigits:d});
 const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
 const colors=["#18753c","#75d7a2","#1683a6","#a76617","#296e77","#c39a32"];
 function section(kicker,title,content,note=""){return `<section class="section"><div class="section-head"><div><small>${kicker}</small><h2>${title}</h2></div>${note?`<p>${note}</p>`:""}</div>${content}</section>`}
 function donut(title,items,centerValue,centerLabel){let cursor=0;const stops=items.map((item,i)=>{const start=cursor;cursor+=item.pct;return `${colors[i]} ${start}% ${cursor}%`}).join(",");return `<article class="chart-card visual-card"><h3>${title}</h3><div class="donut-layout"><div class="donut" style="--segments:${stops}" role="img" aria-label="${items.map(i=>`${i.label} ${i.pct}%`).join(", ")}"><div><strong>${centerValue}</strong><span>${centerLabel}</span></div></div><div class="chart-legend">${items.map((item,i)=>`<div><i style="--swatch:${colors[i]}"></i><span>${item.label}</span><b>${fmt(item.pct,1)}%</b></div>`).join("")}</div></div></article>`}
 function bars(title,items,tone="green"){return `<article class="chart-card ${tone}"><h3>${title}</h3>${items.map(item=>`<div class="bar-row"><span title="${esc(item.label)}">${esc(item.label)}</span><div class="bar-track"><i style="--pct:${Math.min(100,item.pct)}%"></i></div><b>${item.value}</b></div>`).join("")}</article>`}
 function render(p){currentProfile=p;const isEpci=type==="epci";document.title=`${p.name} · Nature et adaptation · DDT 95`;headerTitle.textContent=isEpci?"Fiche EPCI":"Fiche communale";const otherVeg=Math.max(0,100-p.vegetation_pct),otherReservoir=Math.max(0,100-p.reservoir_pct);root.innerHTML=`<div id="report"><section class="report-cover"><div class="cover-kicker">FICHE ${isEpci?"INTERCOMMUNALE":"COMMUNALE"} · NATURE ET ADAPTATION</div><h1>${esc(p.name)}</h1><p>Où sont les réservoirs de nature, comment l’eau et la végétation soutiennent-elles le territoire, et quelles continuités dépassent ses limites ?</p><div class="cover-meta"><span>IGN · INPN · SDRIF-E</span><span>${isEpci?`${p.members.length} communes · EPCI ${p.code}`:`Commune ${p.code}`}</span><span>DDT du Val-d’Oise</span><span>Référentiels 2026</span></div></section><div class="report-body">
 ${section("01 · REPÈRES",`${isEpci?"L’EPCI":"La commune"} en six chiffres`,`<div class="kpi-grid kpi-grid-six"><div class="kpi population-kpi"><small>Surface du territoire</small><strong>${fmt(p.area_ha)} ha</strong><span>surface calculée en Lambert-93</span></div><div class="kpi"><small>Couvert végétalisé</small><strong>${fmt(p.vegetation_pct,1)}%</strong><span>${fmt(p.vegetation_ha)} hectares</span></div><div class="kpi"><small>Réservoirs de nature</small><strong>${fmt(p.reservoir_pct,1)}%</strong><span>${fmt(p.reservoir_ha)} hectares sans double compte</span></div><div class="kpi"><small>Cours d’eau</small><strong>${fmt(p.water_km,1)} km</strong><span>${fmt(p.water_density,2)} km par km²</span></div><div class="kpi"><small>Connexions régionales</small><strong>${fmt(p.connections)}</strong><span>connexions du SDRIF-E</span></div><div class="kpi"><small>Observations agrégées</small><strong>${fmt(p.observations)}</strong><span>${p.last_observation?`dernière observation ${p.last_observation}`:"millésime non renseigné"}</span></div></div>`)}
 ${section("02 · SOCLE NATUREL","Végétation et réservoirs",`<div class="charts-grid visual-grid">${donut("Couvert végétalisé",[{label:"Espaces végétalisés",pct:p.vegetation_pct},{label:"Autres espaces",pct:otherVeg}],`${fmt(p.vegetation_pct,1)}%`,"du territoire")}${donut("Réservoirs inventoriés ou protégés",[{label:"Réservoirs de nature",pct:p.reservoir_pct},{label:"Reste du territoire",pct:otherReservoir}],`${fmt(p.reservoir_pct,1)}%`,"du territoire")}</div>`,`Les surfaces qui se chevauchent sont dissoutes afin d’éviter les doubles comptes.`)}
 ${section("03 · CONNEXIONS ET EAU","Les appuis qui relient le territoire",`<div class="charts-grid">${bars("Poids territorial",[{label:"Couvert végétalisé",pct:p.vegetation_pct,value:`${fmt(p.vegetation_pct,1)}%`},{label:"Réservoirs de nature",pct:p.reservoir_pct,value:`${fmt(p.reservoir_pct,1)}%`},{label:"Densité hydrographique",pct:Math.min(100,p.water_density*40),value:`${fmt(p.water_density,2)}`}])}${bars("Repères de continuité",[{label:"Cours d’eau",pct:Math.min(100,p.water_km/2),value:`${fmt(p.water_km,1)} km`},{label:"Connexions SDRIF-E",pct:Math.min(100,p.connections*12),value:fmt(p.connections)},{label:"Couvert végétalisé",pct:p.vegetation_pct,value:`${fmt(p.vegetation_pct,1)}%`}],"orange")}</div>`,`Les connexions du SDRIF-E sont prévues pour une lecture régionale et non parcellaire.`)}
 ${section("04 · CONNAISSANCE","Ce que les données permettent de lire",`<div class="rank-grid"><div class="rank-list"><h3>Principaux appuis</h3><div class="rank-row"><span>Couvert végétalisé</span><b>${fmt(p.vegetation_ha)} ha</b></div><div class="rank-row"><span>Réservoirs de nature</span><b>${fmt(p.reservoir_ha)} ha</b></div><div class="rank-row"><span>Réseau hydrographique</span><b>${fmt(p.water_km,1)} km</b></div></div><div class="rank-list"><h3>Points de vigilance</h3><div class="rank-row"><span>Échelle des connexions</span><b>1:150 000</b></div><div class="rank-row"><span>Observations naturalistes</span><b>effort variable</b></div><div class="rank-row"><span>Fraîcheur</span><b>potentiel</b></div></div></div>`)}
 ${section("SOURCE · MÉTHODE","Bien lire cette fiche",`<div class="method-note"><strong>Sources :</strong> IGN BD TOPO pour la végétation et l’eau ; INPN / PatriNat pour les ZNIEFF et espaces protégés ; Région Île-de-France / Institut Paris Region pour les connexions du SDRIF-E ; GeoNat’îdF / ARB Île-de-France pour les observations agrégées. Une ZNIEFF est un inventaire de connaissance et non une protection réglementaire. Une absence d’observation ne signifie pas une absence d’espèce. Les EPCI sont limités à leur partie val-d’oisienne. La lecture « appuis de fraîcheur » décrit un potentiel lié à la végétation et à l’eau, pas une température mesurée.</div>`)}
 </div></div>`}
 fetch(`data/${type}_profiles.json`).then(r=>r.json()).then(data=>{if(!data[id])throw Error();render(data[id])}).catch(()=>root.innerHTML='<div class="loading">Impossible de charger cette fiche territoriale.</div>');
 document.getElementById("openExport").onclick=()=>dialog.showModal();document.getElementById("closeExport").onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};document.getElementById("printProfile").onclick=()=>{dialog.close();window.print()};
 document.getElementById("makePdf").onclick=async()=>{dialog.close();document.body.classList.add("exporting");const name=currentProfile.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/gi,"-").toLowerCase();try{await html2pdf().set({margin:0,filename:`fiche-nature-adaptation-${name}.pdf`,image:{type:"jpeg",quality:.96},html2canvas:{scale:2,useCORS:true,letterRendering:true},jsPDF:{unit:"mm",format:"a4",orientation:"portrait"},pagebreak:{mode:["css","legacy"],avoid:[".section",".chart-card"]}}).from(document.getElementById("report")).save()}finally{document.body.classList.remove("exporting")}};
})();
